src/article/model/Article.java
package article.model;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class Article {
	private String id;
	private String author;
	private String title;
	private String content;
	private LocalDateTime addedAt;
	private String filename;


	public Article(String id, String author, String title, String content, LocalDateTime addedAt, String filename) {
		this.id = id;
		this.author = author;
		this.title = title;
		this.content = content;
		this.addedAt = addedAt;
		this.filename = filename;
	}

	public LocalDateTime getAddedAt() {
		return addedAt;
	}
	
	public String getAddedAtFormatted() {
		return addedAt.format(DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm:ss"));
	}

	public String getId() {
		return id;
	}

	public String getAuthor() {
		return author;
	}

	public String getTitle() {
		return title;
	}

	public String getContent() {
		return content;
	}

	public String getFilename() {
		return filename;
	}
	
	public String getFilenameFormatted() {
		return filename.substring(filename.indexOf("_") + 1);
	}
}

WebContent/WEB-INF/view/listArticleForm.jsp
<%@page import="article.model.Article"%>
<%@page import="article.model.ArticlePage"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<table>
		<tr>
			<td colspan="4"><a href="/Board4/article/write">[글쓰기]</a></td>
		</tr>
		<tr>
			<td>번호</td>
			<td>제목</td>
			<td>작성자</td>
			<td>작성일자</td>
		</tr>
		<c:forEach var="article" items="${articlePage.articles }">
			<tr>
				<td>${article.id }</td>
				<td><a href="/Board4/article/read?article_id=${article.id }">${article.title }</a></td>
				<td>${article.author }</td>
				<td>${article.addedAtFormatted }</td>
			</tr>
		</c:forEach>
		<tr>
			<td colspan="4"><c:if
					test="${articlePage.startPage > articlePage.pagesPerBlock }">
					<a
						href="/Board4/article/list?curPage=${articlePage.startPage - 1 }">[이전]</a>
				</c:if> <c:forEach var="pageNo" begin="${articlePage.startPage}"
					end="${articlePage.endPage }">
					<a href="/Board4/article/list?curPage=${pageNo }">${pageNo }</a>
				</c:forEach> <c:if test="${articlePage.endPage < articlePage.pageCount }">
					<a href="/Board4/article/list?curPage=${articlePage.endPage + 1 }">[다음]</a>
				</c:if></td>
		</tr>
	</table>
</body>
</html>

WebContent/WEB-INF/view/modifyArticleForm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<form action="/Board4/article/modify" method="post" enctype="multipart/form-data">
	<input type="hidden" name="article_id" value="${article.id }"/>
			작성자:<input type="text" name="author" value="${article.author }"> 제목:<input type="text" name="title" value="${article.title }">
		내용:
		<textarea rows="5" cols="30" name="content">${article.content }</textarea>
		파일:<input type="file" name="file1">
		<input type="submit" value="수정" />
	</form>
</body>
</html>

WebContent/WEB-INF/view/readArticle.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<p>제목:${article.title }</p>
	<p>작성자:${article.author }</p>
	<p>
		내용:<span>${article.content }</span>
	</p>
	<p>
		파일:
		<c:if test="${ ! empty article.filename}">
			<a href="/Board4/article/file?article_id=${article.id }">${article.filenameFormatted}</a>
		</c:if>
	</p>
	<a href="/Board4/article/modify?article_id=${article.id }">[수정]</a>
	<a href="/Board4/article/delete?article_id=${article.id }">[삭제]</a>
</body>
</html>

WebContent/WEB-INF/view/writeArticleForm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<form action="/Board4/article/write" method="post" enctype="multipart/form-data">
		작성자:<input type="text" name="author"> 제목:<input type="text" name="title">
		내용:
		<textarea rows="5" cols="30" name="content"></textarea>
		파일:<input type="file" name="file1">
		<input type="submit" value="등록" />
	</form>
</body>
</html>